#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Write a short tagline for your app.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Thirdly
your_link: https://thirdly.co
your_city: Arizona
email_address: hello@thirdly.co
facebook_username:
instagram_username:
twitter_username:
github_username:
youtube_username:
mastodon_link:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Spelling Test
    description: Each of your spelling words is pronounced just like a standard spelling test. Enter each word from your spelling list one by one until you've spelled all the words.
    fontawesome_icon_name: #magic

  - title: Flash Cards
    description: Pactice your spelling words with flash cards. Each word is pronounced and used in a sentence to help you learn to spell the word. 
    fontawesome_icon_name: #mobile

  - title: Word Search
    description: Word sprout places words from your spelling list into your very own word search. Find every word in the word bank to complete the puzzle.
    fontawesome_icon_name: #play-circle

  - title: Sight Words
    description: Choose between Fry and Dolch sight words. Over 1000 words to practice and learn.
    fontawesome_icon_name: #sync


# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Jekyll Configuration
baseurl                                   : "/"
url                                       : "https://wordsprout.co"

sass:
  style: :compressed

exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/
